language: php
sudo: false
dist: trusty
php:
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - composer install -o --prefer-dist --no-interaction

script:
  - if [[ $(find . \( -name '*.php' \) -not -path "./vendor/*" -exec php -lf {} \; | grep -v '^No syntax errors') ]] ; then exit 1 ; fi
  - composer run-script test
